name              'freebsd'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Handles FreeBSD ports setup'
version           '2.0.4'
source_url        'https://github.com/sous-chefs/freebsd'
issues_url        'https://github.com/sous-chefs/freebsd/issues'
chef_version      '>= 15.3'

supports 'freebsd'
